# This workflow will distribute the Android app to testers
name: Review Distribute

on:
  issue_comment:
    types: [ created ]

jobs:
  build_and_distribute:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '!SEND_ME_AT') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for executables
        run: |
          chmod +x gradlew
          chmod +x .github/encrypted_secrets/decrypt_secrets.sh
          chmod +x .github/exports.sh
      - name: Decrypt Secrets
        env:
          SECRETS_DECRYPT_PASSPHRASE: ${{ secrets.SECRETS_DECRYPT_PASSPHRASE }}
        run: .github/encrypted_secrets/decrypt_secrets.sh
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Extract testers
        id: extract_testers
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          source .github/exports.sh
          testers=$(format_command "$COMMENT" command SEND_ME_AT)
          echo "::set-output name=testers::${testers}"

      - name: Distribute with Firebase App Distribution
        if: ${{ contains(steps.extract_testers.outputs.testers, '@') }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          TESTERS: ${{ github.steps.extract_testers.outputs.testers }}
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
        run: |
          source .github/exports.sh
          notes=$(echo "REVIEW: \n${TITLE} \n$(format_command "$BODY" text)" | tr -s " ")
          ./gradlew appDistributionUploadDebug -Pdist_testers="$TESTERS" -Pdist_notes="$notes"