# This workflow will distribute the Android app to testers
name: Test Distribute

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  schedule:
    - cron: "0 2 * * 0-6"

  workflow_dispatch:

jobs:
  check:
    outputs: 
      should_run: ${{ steps.check.outputs.should_run }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant exec permissions for check_CD.sh 
        run: chmod +x .github/check_CD.sh
      - name: check
        id: check
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
          TITLE: ${{github.event.pull_request.title}}
          BODY: ${{github.event.pull_request.body}}
        run: .github/check_CD.sh

  build_and_distribute:
    needs: check
    if: needs.check.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for executables
        run: |
          chmod +x gradlew
          chmod +x .github/encrypted_secrets/decrypt_secrets.sh
          chmod +x .github/exports.sh
      - name: Decrypt Secrets
        env:
          SECRETS_DECRYPT_PASSPHRASE: ${{ secrets.SECRETS_DECRYPT_PASSPHRASE }}
        run: .github/encrypted_secrets/decrypt_secrets.sh
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Distribute with Firebase App Distribution
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          source .github/exports.sh
          ./gradlew appDistributionUploadDebug -Pdist_groups="$(get_value_at_key "$DIST_GROUPS")" \
              -Pdist_notes="$(get_value_at_key "$RELEASE_NOTES")"
          set_value_at_key "$RELEASE_NOTES" ""
          set_value_at_key "$DIST_GROUPS" "$(get_value_at_key "$PERSISTED_GROUPS")"
